import type { Experience } from '@/types/experience';

export const experiences: Experience[] = [
  {
    id: 'banpro',
    company: 'Banpro Grupo Promerica',
    role: 'Senior Systems Analyst & Developer',
    startDate: '2020',
    current: true,
    location: 'Managua, Nicaragua',
    summary:
      'Designing and maintaining enterprise banking systems, integrations, payment solutions, and secure transactional platforms in the financial sector.',
    responsibilities: [
      'Built and maintained enterprise REST and SOAP integrations using Oracle Service Bus (OSB).',
      'Developed internal banking applications using React, .NET Core, and Oracle APEX.',
      'Implemented payment gateway integrations with Cybersource and Visa.',
      'Designed and optimized PL/SQL procedures, packages, and high-volume transactional processes.',
      'Developed secure Android applications for internal banking operations.',
      'Worked on mission-critical financial systems with high availability requirements.',
    ],
    technologies: [
      { name: 'Oracle', category: 'database' },
      { name: 'PL/SQL', category: 'database' },
      { name: 'Oracle Service Bus', category: 'backend' },
      { name: '.NET Core', category: 'backend' },
      { name: 'React', category: 'frontend' },
      { name: 'Android', category: 'mobile' },
      { name: 'Kotlin', category: 'mobile' },
      { name: 'SQL Server', category: 'database' },
      { name: 'JWT', category: 'backend' },
      { name: 'REST API', category: 'backend' },
      { name: 'SOAP', category: 'backend' },
    ],
  },
  {
    id: 'intur',
    company: 'Instituto Nicaragüense de Turismo (INTUR)',
    role: 'Software Developer',
    startDate: '2017',
    endDate: '2020',
    current: false,
    location: 'Managua, Nicaragua',
    summary:
      'Developed and maintained tourism management systems and internal workflow automation solutions.',
    responsibilities: [
      'Built enterprise modules using Spring Framework, Hibernate, and JSF.',
      'Developed backend business logic and database integrations.',
      'Improved internal workflows and reporting systems.',
      'Participated in full software development lifecycle from analysis to deployment.',
    ],
    technologies: [
      { name: 'Java', category: 'backend' },
      { name: 'Spring', category: 'backend' },
      { name: 'Hibernate', category: 'backend' },
      { name: 'JSF', category: 'frontend' },
      { name: 'PrimeFaces', category: 'frontend' },
      { name: 'PostgreSQL', category: 'database' },
      { name: 'REST API', category: 'backend' },
      { name: 'SOAP', category: 'backend' },
    ],
  },
  {
    id: 'caf',
    company: 'Central American Fisheries',
    role: 'Junior Programmer',
    startDate: '2016',
    endDate: '2017',
    current: false,
    location: 'Managua, Nicaragua',
    summary: 'Customized ERP modules and automated accounting and operational business processes.',
    responsibilities: [
      'Administered Adempiere ERP on Debian Linux servers.',
      'Developed and maintained Java-based modules and reports using iReport.',
      'Oversaw PostgreSQL database backups and performance tuning.',
      'Provided support and training to internal users.',
    ],
    technologies: [
      { name: 'Java', category: 'backend' },
      { name: 'PostgreSQL', category: 'database' },
      { name: 'Adempiere ERP', category: 'backend' },
      { name: 'Linux', category: 'infrastructure' },
    ],
  },
];
